[project]
name = "{{PROJECT_NAME}}"
version = "0.1.0"
requires-python = "==3.14.*"
dependencies = []

[dependency-groups]
dev = [
    "basedpyright==1.39.9",
    "hypothesis==6.160.0",
]

[tool.basedpyright]
typeCheckingMode = "all"
pythonVersion = "3.14"
include = ["{{MODULE_NAME}}", "tests"]
reportMissingTypeStubs = "none"
reportUnusedCallResult = "error"
reportUnnecessaryTypeIgnoreComment = "error"
